### ISSUE TITLE
4-digit weather file - strange behavior

### ISSUE THREAD

**Issue by chporter** [DSSAT/dssat-csm-os#234]
We generated a slightly imperfect 4-digit weather file using the AgMIP DSSAT translator and got some unexpected results. The format of the file did not have the 2-spaces between the "@" and "DATE" on the header line (i.e., `@DATE    SRAD` instead of `@  DATE  SRAD`). The model ran, but values of SRAD were interpreted incorrectly and the model results were very bad. But there was no error message. 

Actually, the more I think about it, the model is behaving correctly because it is trying to right-justify data under the headers. Let's review this at a mini-sprint, but maybe we do nothing.

**Comment by fabiooliveira72** [comment]
Hi Cheryl!

Yes, indeed. The weather subroutine has some routines that work with the header spaces in the weather file. If the file are not right justified in the header based on the data, even for Y2K will not work. This is some flexibility that we always had in the weather subroutine but only if the header is right justified.

The @ in the beginning of the file needs to be in the first column (first character place) of the file because the IGNORE, IGNORE2 subroutines will not work.

Please let me know if I can help with anything else

Thank you so much,

Fabio Oliveira
