### ISSUE TITLE
"Utilities/run_dssat" is not created on WIN32 platforms, but is unconditionally used when installing.

### ISSUE THREAD

**Issue by sielenk-yara** [DSSAT/dssat-csm-os#25]
The CMakeLists.txt specifies the creation of the file conditionally:
```CMake
[...]
IF(WIN32)
    SET(OSDefinitions "Utilities/OSDefsWINDOWS.for")
    add_definitions(-DWIN32=1})
ELSE()
[...]
	configure_file(
		"${PROJECT_SOURCE_DIR}/Utilities/run_dssat.in"
		"${PROJECT_SOURCE_DIR}/Utilities/run_dssat"
	)
ENDIF(WIN32)
[...]
```
but mentions it unconditionally when specifying what to install:
```CMake
[...]
install(FILES Utilities/run_dssat DESTINATION .
	PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE
	)
[...]
```

This caused the Visual Studio 2019 build of the install-project to fail on the system of @GangaRamMaharjan.
The Visual Studio project files were generated with the CMake 3.18.1 GUI.

Also wrapping the install code with ```IF(WIN32)``` and ```ENDIF(WIN32)``` fixed the problem, IIRC.

**Comment by fabiooliveira72** [comment]
Hi Sielenk!

I believe there is a confusion here. The run_dssat is only used by Linux or MacOS systems during the make install. If there was a problem is related to something else the fail.

I am closing this issue due to several testing of different developer tools and they are working fine. If you still have problems please let us know!

Thank you for your interest in DSSAT!
