### ISSUE TITLE
Example Experiment and Weather Files using 4 digit year

### ISSUE THREAD

**Issue by helsharif** [DSSAT/dssat-csm-os#338]
Hello,
I am trying to create some experiment and weather files that use 4-digit year + doy convention (YYYYDDD). However when I try to run such files, DSSAT throws and error saying it cannot read the planting date from my experiment file. It also says "Not able to find 7-digits first weather date". I have been struggling to find information on how to appropriately write the headers and data for experiment and weather files using 4 digit years. Can someone post an example experiment file and weather file that shows the proper way to set this up?
Best regards

This attached zip has my example experiment and weather files that currently do not work. In this experiment I want to plant on day 91 of year 2002.
[current_exp_and_wth.zip](https://github.com/DSSAT/dssat-csm-os/files/11995878/current_exp_and_wth.zip)

**Comment by helsharif** [comment]
I just received access to download the Windows DSSAT 4.8 and I reviewed the help file that has the example 4 digit year weatherfile specification. I followed the instructions, namely that "Data must be right justified under header." However, my weatherfile would still fail to be recognized by DSSAT with the 4 digit year. (The file worked fine if I used the 2 digit year).

Then I noticed that in the example 4-digit year weatherfile in the DSSAT 4.8, the first line reads:
$WEATHER DATA :

while in the example 2-digit year weatherfile the first line reads:
*WEATHER DATA :

I noticed that the 4-digit year file starts with a dollar sign "$" instead of an asterix "*". 

So I went in my weatherfile and simply changed the starting * to $ and now my weatherfile works (see attached):
[corrected_4digit_weather_file.zip](https://github.com/DSSAT/dssat-csm-os/files/11997617/corrected_4digit_weather_file.zip)

If the developers could make a change so that the weatherfile would not be so sensitive to the * or $ (or at least have some documentation clearly mentioning this issue) that would be great, since I don't think the fix is obvious.

**Comment by fabiooliveira72** [comment]
Hi @helsharif!

Yes, this difference between the '$'and '*' sign we have to keep it because of the backwards compatibility. There is other ways that can modify this in the future but we need to always keep in mind old versions and users. There is a limited flexibility in the source code to do this.

About the documentation I am glad you found something and could correct your file. We have a intensive Workshop occurring in May, 2024 (unfortunately just happened the last one) that we show an example and difference between 4-digit and 2-digit year in the weather file for the workshop participants. Please see more information at https://dssat.net/

Thank you!

Fabio Oliveira
