### ISSUE TITLE
Error on compile in linux

### ISSUE THREAD

**Issue by ciskoh** [DSSAT/dssat-csm-os#375]
Hi all, 
I am trying to compile DSSAT (release branch) on linux ubuntu using gfortran compiler following the instructions on the website. Also I am not familiar with Fortran or compiling, so sorry for the basic question:
I encounter an error upon giving the command:
```
cmake -DCMAKE_INSTALL_PREFIX=./dssat-csm-os/Data -DCMAKE_BUILD_TYPE=RELEASE ./dssat-csm-os
```
The error is 
```
CMake Error at cmake/Modules/SetCompileFlag.cmake:110 (MESSAGE):
  No compile flags were found
Call Stack (most recent call first):
  cmake/Modules/SetFortranFlags.cmake:153 (SET_COMPILE_FLAG)
  CMakeLists.txt:78 (INCLUDE)
```
I am wondering if it could be a problem with gfortran compiler, my installed version is `GNU Fortran (conda-forge gcc 13.2.0-1) 13.2.0` . Any idea what could I be doing wrong?

More in general, looking at the CMakeList.txt and the SetFortranFalgs.cmake I see a lot of suggestions on adapting those flags, but I do not understand if and how should I modify them. Can somebody guide me through that?

Many thanks in advance

**Comment by fabiooliveira72** [comment]
Hi @ciskoh 

I am not in front of my computer to test this command line but I think there isca problem there.

Please, try to compile inside the root directory (dssat-csm-os)

Create a build folder and cd on it

Then,

Cmake -Dcmakeprefix=yourpath -Dcmakebuildtype=RELEASE ..

That is it!

Thank you!

**Comment by frostbytten** [comment]
Due to a weird gfortran bug, I had to remove the REQUIRED flag on lines 151 and 187 in the cmake/Modules/SetFortranFlags.cmake file. It seems you are running into the same problem. On Sep 20, 2023, at 09:32, Fabio Oliveira ***@***.***> wrote:﻿
Hi @ciskoh
I am not in front of my computer to test this command line but I think there isca problem there.
Please, try to compile inside the root directory (dssat-csm-os)
Create a build folder and cd on it
Then,
Cmake -Dcmakeprefix=yourpath -Dcmakebuildtype=RELEASE ..
That is it!
Thank you!

**Comment by fabiooliveira72** [comment]
Hi @frostbytten 

Thanks for checking on this!

I will check later on too and test it. If there is a PR a can accept and create a tag later.

Thank you!

**Comment by ciskoh** [comment]
Thank you both for the super quick answer!

 I have commented out the following flags in `SetFortanFlags.cmake`:
(line 153-157)
```
SET_COMPILE_FLAG(CMAKE_Fortran_FLAGS_DEBUG "${CMAKE_Fortran_FLAGS_DEBUG}"
                 Fortran REQUIRED "/Od" # Intel Windows
                                  "-Og" # GNU better debugging flag
                                  "-O0" # All compilers not on Windows
                )
```
and (line 188-192)
```
SET_COMPILE_FLAG(CMAKE_Fortran_FLAGS_TESTING "${CMAKE_Fortran_FLAGS_TESTING}"
                 Fortran REQUIRED "/O2" # Intel Windows
                                  "-O2" # All compilers not on Windows
                )
```

I have also launched the cmake command from `dssat-csm-os/build` as follows:

```
cmake -DCMAKE_INSTALL_PREFIX=/home/matt/DigitSoil/agroecological_models/dssat-csm-os/build -DCMAKE_BUILD_TYPE=RELEASE ..
```
and the command completes. However now when I launch the `make`command I receive the following error:
```
[ 99%] Building Fortran object CMakeFiles/dscsm048.dir/Weather/SOLAR.for.o
[ 99%] Building Fortran object CMakeFiles/dscsm048.dir/Weather/weathr.for.o
[ 99%] Building Fortran object CMakeFiles/dscsm048.dir/Weather/WGEN.for.o
[ 99%] Building Fortran object CMakeFiles/dscsm048.dir/Weather/WTHMOD.for.o
[100%] Linking Fortran executable bin/dscsm048
/home/matt/miniconda3/envs/dssat/bin/../lib/gcc/x86_64-conda-linux-gnu/13.2.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lquadmath: No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/dscsm048.dir/build.make:8121: bin/dscsm048] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/dscsm048.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

I verified and I do have the relevant library `gcc` installed . Any idea of what could be the problem now?
Also, is my MAKE_INSTALL_PREFIX in my case ("/home/matt/DigitSoil/agroecological_models/dssat-csm-os/build") correct or should I remove the "/build"?

**Comment by frostbytten** [comment]
There are a couple of issues, which long term might need to be dealt with by the DSSAT team.

1. Anaconda does not install the static version of libquadmath. I haven't found an up-to-date package which has this library. Depending on **how** you installed the gfortran compiler in conda, you might be able to install libgfortran-static on your actual machine and it work. But this is a huge might.
2. DSSAT is a static binary, so the static libraries for all the dependencies are required in order to build the final product.

At this point, you can either try to build on the native machine without anaconda or set up a containerized build for yourself (distrobox, docker, etc.). This is primarily an anaconda issue.

**Comment by ciskoh** [comment]
thank you for explaining this. I figured as well that it was a problem of
anaconda, since installing gfortran from apt worked and wasn't giving the
same error!
