### ISSUE TITLE
How to calculate the missing values in SBuild tool

### ISSUE THREAD

**Issue by JongChao** [DSSAT/dssat-csm-os#426]
Hi,
The SBuild tool can calculate missing values, including SLL, SDUL, SAT, SSKS, BD, and SRGF, according to some basic soil paremeters.
What's the method used here? 
I'm preparing soil data by R. Where can I find related code of these method?
Hope to get your help.
![SBuild](https://github.com/DSSAT/dssat-csm-os/assets/149078551/65e4a877-f744-4fec-9333-4c77bcbe2b47)

**Comment by lpmorenoc** [comment]
Hi @JongChao, I recommend reading the following papers, which can give some details on some of the pedotransfer functions that DSSAT uses based on the available soil variables (e.g., Table 1 of Gijsman et al., 2002).  Because this is a question about the model use more  than the code, next time, you can submit your question in the following link https://dssat.net/contact-us/

Baumer, O.W., and Rice, J.W. 1988. Methods to predict soil input data for DRAINMOD. ASAE Paper No. 88-2564. 
  
 

 
  
 

Ritchie,.J.T., Godwin, D.C., Singh, U. 1989. Soil and Water inputs for IBSNAT crop models. In DSSAT. IBSNAT Symposium. Part I. Las Vegas, Nevada. Pp.31-47 
  
 

 
  
 

Rawls, W.J., and Brakensiek, D.L. 1985. Prediction of soil water properties for hydrologic modeling. In: Jones, E.B. and Ward, T.J. (Eds.), Proc. Symp. Watershed Management in the Eighties. April 30-May 1, 1985, Denver, CO. Am. Soc. Civil Eng., New York, NY. pp.293-299. 
  
 

 
  
 

Rawls, W.J., Brakensiek, D.L., and Saxton, K.E. 1982. Estimation of soil water properties. Transactions of the ASAE 25, 1316-1328. 
  
 

 
  
 

Saxton, K.E., Rawls, W.J., Romberger, J.S., and Papendick, R.I. 1986. Estimating generalized soil-water characteristics from texture. Soil Sci. Soc. Am. J. 50, 1031-1036. 
  
 

 
  
 

Gijsman, A.J., Jagtap, S.S., Jones, J.W. Wading through a swamp of complete confusion: how to choose a method for estimating soil water retention parameters for crop models. Europ. J.Agronomy 18(2002) 75-105 
  
 

 
  
 

Gijsman, A.J., P.K. Thornton, and G. Hoogenboom. 2007. Using the WISE database to parameterize soil inputs for crop simulation models. Computers and Electronics in Agriculture 56:85-100.
 

[Gijsman et al 2002 how to choose soil water retention parameters.pdf](https://github.com/user-attachments/files/16157683/Gijsman.et.al.2002.how.to.choose.soil.water.retention.parameters.pdf)
[Gijsman_et_al_2007_Using the WISE database to parameterize soil inputs for crop simulation models.pdf](https://github.com/user-attachments/files/16157684/Gijsman_et_al_2007_Using.the.WISE.database.to.parameterize.soil.inputs.for.crop.simulation.models.pdf)

**Comment by JongChao** [comment]
@lpmorenoc Many thanks for your detailed reply. I'll read the paper.
